### ISSUE TITLE
Is it possible to just update the fieldlist?

### ISSUE THREAD

**Issue by KeKs0r** [lucaong/minisearch#106]
Hi,

I came across this library while researching for a more sophisticated filtering solution for a table we are using. We did use `trie-search` before and it started to came to limitations. I am really impressed with the thought and care that went into this and even a simple implementaiton of minisearch already seems to be a much better solution :)

### The Challenge
We are currently using minisearch to do some fulltext instant filtering on a table. The table can have up to 1k documents with up to 40 fields. Currently one of the challenges is, that I need to recreate the index (runtime roughly 1-3 seconds depending on dataset and machine)  when changing the columns.
It would be great if there would be some way of e.g. only remove the index for a single column as well as potentially only add a column and that way extend the index. 

Or is this something I can even do in userland?

**Comment by lucaong** [comment]
Hi @KeKs0r , thanks a lot for the kind words!

It is possible to re-index a single document if you temporarily keep the old version, by first removing the old version, then adding the new one.

It is not currently possible though to re-index only specific fields, or to add fields to an existing index. I will think about whether that could be implemented, as it would be a nice feature.

In order to understand better, in your case you need to re-index a column of your table for all rows, or rather re-index a few columns of a single row that changed?

**Comment by KeKs0r** [comment]
> In order to understand better, in your case you need to re-index a column of your table for all rows, or rather re-index a few columns of a single row that changed?

I actually have both use cases:
1. The user adds columns and I would need to add the index for those columns for all rows
2. the user changes the data in one row and I would need to reindex the values for that single row

> It is possible to re-index a single document if you temporarily keep the old version, by first removing the old version, then adding the new one. If only one document changed, that’s definitely faster than re-indexing the whole collection.

Theoretically it should be possible, it just requires a lot of rewiring, because I don't have the old document around. I am using `mobx` and therefore mutate the actual documents, which makes this a little bit harder.
Would there be a way to delete all values for an id without having the full document?

**Comment by lucaong** [comment]
Checking in just for an update: replacing a document with a new version became a lot easier with the introduction of the `replace` method in `v6.0.0-beta.1` (soon to become `v6.0.0`). See [the documentation](https://lucaong.github.io/minisearch/classes/_minisearch_.minisearch.html#replace) for more info.
