### ISSUE TITLE
How to search for items with an embedded hyphen?

### ISSUE THREAD

**Issue by cmcknight** [lucaong/minisearch#108]
I have a use case for item titles that have embedded hyphens, i.e.:

C-8
AR-7
PGMP-15

I seem to get back a lot of completely unrelated results that do not have the search terms in them. I do find the item I'm looking for about halfway or two-thirds down the list.

This is using the generic search (no ands, etc.). I feel like I'm missing something.

**Comment by JustAnotherArchivist** [comment]
I suspect that this is what you're looking for: https://github.com/lucaong/minisearch#tokenization

Specifically, the default `tokenize` function uses this regular expression for splitting, which includes the hyphen (as part of the `,-/` range): https://github.com/lucaong/minisearch/blob/8c66bd2bb053b83a9d5932d12f3bdcda43c0d3f4/src/MiniSearch.ts#L1239

Both on indexing and on searching, that therefore gets split into `C` and `8` for example and is functionally equivalent to entering `C 8`.

**Comment by lucaong** [comment]
That’s correct @JustAnotherArchivist , the default tokenizer splits by space or punctuation, and `-` is considered punctuation. One solution is to specify a custom `tokenize` function that doesn’t split hyphens.

**Comment by lucaong** [comment]
Closing this issue for now, as the above solution should work. @cmcknight feel free to comment further if necessary, and I will reopen the issue in case.

**Comment by cmcknight** [comment]
Hi All,

Sorry for not replying sooner. I've been sidelined due to an illness.

This makes sense and I agree that it can be closed.
