### ISSUE TITLE
How to perform AND as well as OR search?

### ISSUE THREAD

**Issue by Thomas-1985** [lucaong/minisearch#112]
Hi

I just looked at your library and it seems really great. However i searched the docs and didn't find anything regarding how i can configure minisearch to use an AND-based approach (only return elements which match all strings)

Example:
This text contains some elements

Searching for "text contains an" should return nothing
Searching for "text contains elements" should return the result

I think the behaviour of the library is OR-based, or am i wrong?

Best,
Thomas

**Comment by lucaong** [comment]
Hi @Thomas-1985 ,
you can perform `AND` queries by setting the search option `combineWith: 'AND'`, like in the following example:

```javascript
miniSearch.search('text contains elements', {
  combineWith: 'AND'
})
```

You can find more information [in the docs](https://lucaong.github.io/minisearch/classes/_minisearch_.minisearch.html#combine-with-and).

I hope this helps.

**Comment by lucaong** [comment]
@Thomas-1985 I am closing the issue as the question should be answered, but comment further mentioning me if necessary.
