### ISSUE TITLE
Recommended language support libraries?

### ISSUE THREAD

**Issue by akvadrako** [lucaong/minisearch#113]
I'm looking at using minisearch in place of lunr, but one requirement I have is language support, specifically for English and Dutch.

I see there are a few npm packages with stemmers, stop words, etc. Has anyone had success integrating them with minisearch?

**Comment by lucaong** [comment]
Hi @akvadrako ,
I integrated stemmers in custom applications using MiniSearch in the past, I do not recall the specific one but I can look it up.

That said, I want to share a word of caution: stemmers can help increasing recall, but they often make results confusing for the user, so I found myself relying more and more on fuzzy match instead. Here’s a few reasons why:

  - As you can see in several issues opened on Lunr ([this one](https://github.com/olivernn/lunr.js/issues/38) for example), search results when using a stemmers are confusing.
  - Stemmers are language dependent, but many documents mix languages (like mixing English terms of common use in text written in other languages)
  - Fuzzy match covers many of the cases handled by stemming, and ranks results better by edit distance. Moreover, the `match` field in the results contains the actual terms in the document, which is not the case with stemming.

Of course there are still legitimate use cases for stemming, but I felt it was useful to share my personal experience. I ended up replacing stemming with fuzzy match in more than a few applications in recent years, with better user experience.

**Comment by lucaong** [comment]
Closing the issue for now, but feel free to comment further if necessary.
