### ISSUE TITLE
FYI / use in project

### ISSUE THREAD

**Issue by theprojectsomething** [lucaong/minisearch#117]
Hi there .. just a thanks and fyi that I've used minisearch in a recently published project [re:places](https://github.com/theprojectsomething/re.places) (a drop-in polyfill for Algolia Places), that will be making it's way into [citizensgbr.org](https://citizensgbr.org) and [greatreefcensus.org](https://greatreefcensus.org) sometime soon. There's an acknowledgement on the [demo page](https://theprojectsomething.github.io/re.places/). Cheers!

**Comment by lucaong** [comment]
That is awesome! Thanks for letting me know, this made my morning 🙂 I’ll make sure to mention these sites when I add a section on who uses MiniSearch
