### ISSUE TITLE
Type definitions

### ISSUE THREAD

**Issue by samuelmeuli** [lucaong/minisearch#13]
Hi @lucaong,

Thanks a lot for your work on this awesome library! :)

Type definitions would be a great feature to have when using this library in a TypeScript project.

**Comment by lucaong** [comment]
Hi @samuelmeuli,
Thanks a lot for you kind words :)

Yes, type definitions would be a nice addition. I need to brush up a bit my TypeScript knowledge, but I hope to find the time soon. Of course, pull requests are also welcome :)

**Comment by lucaong** [comment]
I just opened PR #16 adding TypeScript definitions. I am not an active TypeScript user, so I could use some help to validate if the definitions are correctly recognized by TypeScript projects.

It would be awesome if you could try it out and let me know if you encounter any issue.

**Comment by lucaong** [comment]
I merged the pull request and released version `v2.0.5` including TypeScript definitions. It seems to work well in my tests, but as I am not a TypeScript expert, please let me know if you encounter issues.

**Comment by samuelmeuli** [comment]
Will do, thanks a lot for implementing this!
