### ISSUE TITLE
how to correctly search for phone numbers

### ISSUE THREAD

**Issue by MichaelRoger** [lucaong/minisearch#130]
hi,
is there a correct way to easy search for phone numbers?
because you know, people do there search different ways ;-)

kind regards

**Comment by rolftimmermans** [comment]
You probably want to normalise the phone numbers before indexing. You can do this with https://github.com/google/libphonenumber. You want to override the `tokenize` function in the constructor [`options`](https://lucaong.github.io/minisearch/modules/_minisearch_.html#options). 

Then in the [`searchOptions`](https://lucaong.github.io/minisearch/modules/_minisearch_.html#searchoptions-1) you also want to override the `tokenize` function, but this time probably just stripping all non-digits. So now your search query is a string of digits and your indexed phone numbers are normalised. It should now be possible to search on prefix or exact matches (or fuzzy matches).

If you want to search from the end (suffix search) you can simply reverse the phone number during indexing and reverse the search query, and do a prefix search instead.

I hope this helps!

**Comment by rolftimmermans** [comment]
Ok, so if you want to match phone numbers at arbitrary positions, you could tokenise the normalised phone number into multiple terms. After normalisation, in your `tokenize` function, split a phone number into terms, where every term starts at the next character and ends at the end of the string. So, for the normalised number `123456789` you would have the terms `123456789`, `23456789`, `3456789`, `3456789`, `456789`, `56789`, `6789`, `789`, `89`, `9`. This is not as inefficient as it looks, because MiniSearch's internal representation is very compact. You can then do a prefix search and you should get matches for any sequence of digits in arbitrary positions in the phone numbers correctly.

**Comment by lucaong** [comment]
I do not have much to add to @rolftimmermans great suggestions, apart from providing a short example implementation:

```javascript
// Assuming the documents look like these
const documents = [
  { name: 'Ada', phoneNumber: '+49-123-456789' },
  { name: 'Alan', phoneNumber: '0987654321' },
  // ...
]

// This function should normalize the phone number for search. You might want to
// normalize the country prefix here, but for brevity I just remove non-digit characters.
const normalizePhoneNumber = (phoneNumber) => {
  return phoneNumber.replace(/[^\d]/, '')
}

const defaultProcessTerm = MiniSearch.getDefault('processTerm')

// Custom tokenizer for phone numbers
const tokenizePhoneNumber = (phoneNumber) => {
  const tokens = []
  for (let i = 0; i < phoneNumber.length; i++) {
    tokens.push(phoneNumber.slice(i))
  }
  return tokens
}

const defaultTokenize = MiniSearch.getDefault('tokenize')

const miniSearch = new MiniSearch({
  fields: ['name', 'phoneNumber'],
  // Custom term processing
  processTerm: (term, fieldName) => {
    if (fieldName === 'phoneNumber') {
      return normalizePhoneNumber(term)
    } else {
      return defaultProcessTerm(term, fieldName)
    }
  },
  // Custom tokenization
  tokenize: (term, fieldName) => {
    if (fieldName === 'phoneNumber') {
      return tokenizePhoneNumber(term)
    } else {
      return defaultTokenize(term, fieldName)
    }
  }
})

miniSearch.addAll(documents)

// This should return all documents where the phone number contains '345'
miniSearch.search('345', { prefix: true })
```

I would close the issue for now, as the original question is answered, but @MichaelRoger feel free to comment further if you have doubts or other questions.

**Comment by MichaelRoger** [comment]
Just trying to adapt the solution. it seems to habe some kind of heap-problem, because with tokenizing every number it would rase the maximum heap. 🤔

**Comment by MichaelRoger** [comment]
in my opinion the only "real" solution should be something like this:
https://github.com/lucaong/minisearch/issues/151

**Comment by lucaong** [comment]
Hi @MichaelRoger ,

In general, my suggestion is to rely on parsing the phone number and splitting it into different normalized fields. Imagine, for example, that given a number like `+49 157 1234567` you want to enable people to find it when searching in all of these ways:

  - With the complete international prefix, with or without `+` or zeroes, or spaces: `+491571234567`, `00491571234567`, `491571234567`, `0049 157 1234567`
  - Without the international prefix, with or without the initial zero: `1571234567`, `01571234567`
  - Using a prefix of any of those: `00491571234`, `157123`
 
One option would be to index two separate fields, one with international prefix, one without. Normalize both fields by removing non-digits and leading zeroes. Apply the same normalization to the search query, and search both fields with prefix match. Here's a stub of a solution (not tested), assuming that only phone numbers are searched:

```javascript
const documents = [
  { id: 1, phone: '+49 157 1234567' },
  { id: 2, phone: '0049 157 13243546' },
  // etc.
]

const removeInternationalPrefix = (phoneNumber) => {
  // Custom function to remove the international prefix
  // Possibly using a library such as https://gitlab.com/catamphetamine/libphonenumber-js#readme
}

const defaultTokenize = MiniSearch.getDefault('tokenize')

const miniSearch = new MiniSearch({
  // Index the phone field, and the "virtual" phoneNoPrefix field (see later)
  fields: ['phone', 'phoneNoPrefix'],

  // Phone numbers should be tokenized as a single token
  tokenize: (text, fieldName) => {
    if (fieldName === 'phone' || fieldName === 'phoneNoPrefix') {
      return [text]
    } else {
      return defaultTokenize(text, fieldName)
    }
  },

  // Implement a phoneNoPrefix "virtual" field, that is the same as phone,
  // but without international prefix
  extractField: (document, fieldName) => {
    if (fieldName === 'phoneNoPrefix') { return document['phone'] }
    return document[fieldName]
  },

  // Normalize phone numbers removing all non-digits and leading zeroes
  processTerm: (term, fieldName) => {
    if (fieldName !== 'phone' && fieldName !== 'phoneNoPrefix') {
      return term.toLowerCase()
    }
    if (fieldName === 'phoneNoPrefix') {
      term = removeInternationalPrefix(term)
    }
    return term.toLowerCase().replace(/^0+|[^\d]/g, '')
  },

  // Default search options (these only make sense when searching for phone numbers)
  // Basically, the whole input is tokenized as a single token, non-digits and leading
  // zeroes are removed, prefix search is enabled.
  searchOptions: {
    tokenize: (text) => [text],
    processTerm: (term) => {
      return term.toLowerCase().replace(/^0+|[^\d]/g, '')
    },
    prefix: true
  }
})

miniSearch.addAll(documents)

// These should now all give results:
miniSearch.search('+49 157 1234567')
miniSearch.search('0157-123-4567')
miniSearch.search('157')
miniSearch.search('0049157123')
```

**Comment by lucaong** [comment]
Alternatively, the first solution posted before can be made a bit smaller by limiting the suffixes to only those longer than N characters (say at least 3 characters). For that, the `tokenizePhoneNumber` function could become:

```javascript
const minSuffixLength = 3

const tokenizePhoneNumber = (phoneNumber) => {
  const tokens = []
  for (let i = 0; i < phoneNumber.length - minSuffixLength; i++) {
    tokens.push(phoneNumber.slice(i))
  }
  return tokens
}
```

By the way, how many records roughly are you indexing?

**Comment by MichaelRoger** [comment]
it is an internal phonebook for about 60.000 people.

**Comment by lucaong** [comment]
Ok that is indeed quite a large collection, but it should still be feasible.

You could try with the minimum suffix length approach proposed above (I set it to 3, but you could set it to the minimum length that can be searched, which could be longer: if a user should type at least 5 digits, you can set it to 5). Or you might have to increase the heap size.

Also make sure that only phone numbers are tokenized by generating all suffixes. Phone numbers have limited lengths, but other fields when tokenized that way could make the index way too big.

**Comment by lucaong** [comment]
Here is a browser example using the strategy outlined above with 60000 random numbers: https://jsfiddle.net/hmkezgws/. It does use quite a lot of memory, but it works like expected.

Ultimately it's up to you to decide if that's too much memory, but if so, you might need to switch to a search server, or use a brute-force approach (which would use less memory but be much slower).
