### ISSUE TITLE
indexing / storage broken in 4.0.x

### ISSUE THREAD

**Issue by noraj** [lucaong/minisearch#131]
## Description

Since v4.0.0, minisearch is not indexing / storing all the data, some fields are randomly missing.

## Context

- Working version tested: 3.2.0, 3.3.0
- Broken version tested: 4.00, 4.0.2

## Working environment

The [master branch of my project](https://gitlab.com/rawsec/rawsec-cybersecurity-list/-/tree/master) is using [minisearch 3.2.0](https://gitlab.com/rawsec/rawsec-cybersecurity-list/-/blob/master/package.json#L44).

A live website is here: https://inventory.raw.pm/, minisearch is used on the home page.

The search is implement that way in [search.js](https://gitlab.com/rawsec/rawsec-cybersecurity-list/-/blob/master/js/search.js).

![image](https://user-images.githubusercontent.com/16578570/154815621-373227de-a470-4593-99bf-be18b5c0b6a3.png)

## Broken environment

The [dev branch of my project](https://gitlab.com/rawsec/rawsec-cybersecurity-list/-/tree/dev) is using [minisearch 4.0.2](https://gitlab.com/rawsec/rawsec-cybersecurity-list/-/blob/dev/package.json#L44).

**Note**: this is [the only difference between the two branches](https://gitlab.com/rawsec/rawsec-cybersecurity-list/-/compare/master...dev).

To build and serve the website locally:

```bash
npm i # install dependencies
gulp # default will build
gulp server # http server
```

![image](https://user-images.githubusercontent.com/16578570/154815651-1d1b759f-8ac5-41af-976b-5b6e1fdf8d9b.png)

## Details

As you can see in [search.js](https://gitlab.com/rawsec/rawsec-cybersecurity-list/-/blob/master/js/search.js), the data is fetched from [here](https://inventory.raw.pm/api/api.json) (is the same in prod and dev). As the JSON data source is not flat a function ([search.js#L21-68](https://gitlab.com/rawsec/rawsec-cybersecurity-list/-/blob/master/js/search.js#L21-68)) is made to flatten it by adding the category as a new field. You can see the 4 `miniSearch.addAll(xxx)` where the data is actually indexed.
You can also see in [search.js#L2-3](https://gitlab.com/rawsec/rawsec-cybersecurity-list/-/blob/master/js/search.js#L2-3) which fields are used for searching and those which are stored for latter display in results.

With 3.2.0 all field are index / stored normally, ex:

![image](https://user-images.githubusercontent.com/16578570/154815896-aa7d992a-7711-48db-af62-3543a7680105.png)

In 4.0.0 many are randomly missing, ex:

![image](https://user-images.githubusercontent.com/16578570/154815916-ea3a8783-5a07-4e2b-b715-a950939a2c10.png)

By adding `console.log(xxx);` just before `miniSearch.addAll(xxx);` you can see that the data passed to minisear for indexing is complete:

![image](https://user-images.githubusercontent.com/16578570/154816122-7f9dc357-3a17-40b8-85b6-a4a7e6faefbd.png)

But in minisearch output, for this example, the category, online, price fields have disappeared.

![image](https://user-images.githubusercontent.com/16578570/154816143-23cbb491-8ac5-4af7-a96a-af5ed8f7c0d8.png)

**Comment by rolftimmermans** [comment]
Thanks for the report! I opened #132 to address this.

**Comment by lucaong** [comment]
Thanks @noraj for the detailed report and @rolftimmermans for the fix. I will make a new release this morning including this fix.

**Comment by lucaong** [comment]
The bugfix release `4.0.3` is now  published on NPM. Thanks everybody!

**Comment by noraj** [comment]
Thanks @rolftimmermans for the fix and @lucaong for the release :)
