### ISSUE TITLE
Exlude newline characters

### ISSUE THREAD

**Issue by samuelmeuli** [lucaong/minisearch#14]
Shouldn't newline characters (`\n` and `\r`) also be part of the [tokenizer regex](https://github.com/lucaong/minisearch/blob/df51fd963a0cd7ae4d4722115b3fdd089e61a63f/src/MiniSearch.js#L657)?

Otherwise, words at the start of a new line won't be matched by a search since the preceding newline chars are added to the start of that term.

**Comment by lucaong** [comment]
That sounds right. I am traveling now, but as soon as I am back I will add a test case for that, and if I confirm the bug I will produce a fix.

Thanks a lot for reporting this

**Comment by lucaong** [comment]
Although, there is already a test case for this, and it seems to pass fine: https://github.com/lucaong/minisearch/blob/master/src/MiniSearch.test.js#L453

I will double check, but newline characters should be already part of the tokenizer regexp ranges.

**Comment by samuelmeuli** [comment]
I think that's because in your test case, there are spaces (the indentation) between the newline character and the word you're searching for.

I can work on a PR if you'd like :)

**Comment by lucaong** [comment]
Sure, a PR would be awesome :)

**Comment by lucaong** [comment]
I will create a new release including your fix later today. Thanks a lot for the PR!

**Comment by samuelmeuli** [comment]
Awesome, thank you!
