### ISSUE TITLE
Search tokens search behavior

### ISSUE THREAD

**Issue by FrancescoBonizzi** [lucaong/minisearch#140]
First of all thanks for you library: its really useful and impressful 😁

Consider this index definition: 

```
const searchFields = ['id', 'brand', 'name'];

const databaseIndex = new MiniSearch({
    fields: searchFields,
    searchOptions: {
        prefix: true,
    },
});
```

I add the items to the index like this:
```
databaseIndex.addAll(rawProductsList);
```

Consider a simple set of objects like this:
| id | brand   | name    |   |   |
|----|---------|---------|---|---|
| 0  | oreo    | biscuit |   |   |
| 1  | barilla | biscuit |   |   |
|    |         |         |   |   |

- When I search for `oreo` i get the row 0
- When I search for `biscuit` both rows
- But when I search for `oreo biscuit` it returns both rows: I would like to get only the row 0. 

It seems that the tokenized search terms are used as `OR` instead of `AND`. 

Is there the possibility to specify a different behavior? 
Thanks a lot!

**Comment by lucaong** [comment]
Hi @FrancescoBonizzi ,
Thanks for the kind words. Yes, the search terms are combined with `OR` by default, but you can change that by setting the `combineWith` search option. Adapting from your example, this should give you the result you want:

```javascript
databaseIndex.search('oreo biscuit', { combineWith: 'AND' })
```

**Comment by rolftimmermans** [comment]
> Is there the possibility to specify a different behavior?

Absolutely! You can do the following:

```
databaseIndex.search("oreo biscuit", {combineWith: "AND"})
```

**Comment by FrancescoBonizzi** [comment]
That's perfect, I already implemented it and I works like a charm. I then read the documentation better and It was specified, sorry for asking it without reading the documentation carefully.

**Comment by lucaong** [comment]
No problem :) welcome to ask
