### ISSUE TITLE
On NPM minisearch 5.0.0-beta1 is tagged has 'latest' instead of 'next'

### ISSUE THREAD

**Issue by xfournet** [lucaong/minisearch#141]
![image](https://user-images.githubusercontent.com/461943/156928646-94fc8866-59ef-4551-bbf1-5e1ef62d5012.png)

**Comment by lucaong** [comment]
Hello @xfournet ,
you are right, @next would have been better. On the other hand, this beta is considered stable, and mostly meant to test the changes to the scoring algorithm in the wild. I expect to release `v5.0.0` soon.

**Comment by xfournet** [comment]
Hi @lucaong,
thanks for your quick reply. Ok i will wait for the v5.0.0
