### ISSUE TITLE
Put weights on values

### ISSUE THREAD

**Issue by rickdio** [lucaong/minisearch#147]
Hi there,

I was wondering if it is possible put weights on specific values of keys besides on the key itself.

My use case is that my documents would have a `type` key, this would be an enum.
And I would like the results to be in favour of a `type`.

```
enum ContentType { BOOK, LETTER, MOVIE }

const document = [
  {
    id: 'my-id',
    title: 'my title',
    type: ContentType.BOOK
  },
  {
      id: 'my-id',
      title: 'my movie title',
      type: ContentType.MOVIE
    }
]
```

With the above as a example of my document, I want to be able to put more weight on a ContentType when I search.

My question would be if this is already possible, if this would be a future feature or can I help with implementing this?

**Comment by lucaong** [comment]
Hi @rickdio ,
yes, this is possible by using the `boostDocument` search option, which is admittedly not too easy to find in the [documentation](https://lucaong.github.io/minisearch/modules/_minisearch_.html#searchoptions-1):

> boostDocument?: undefined | ((documentId: any, term: string) => number)
>
> Function to calculate a boost factor for documents. It takes as arguments the document ID, and a term that matches the search in that document, and should return a boosting factor.

In your case, you could use it like this:

```javascript
// Create a mapping of documents by ID, that we will use later
const docById = documents.reduce((byId, doc) => {
  byId[doc.id] = doc
  return byId
}, {})

const miniSearch = new MiniSearch({
  fields: ['title'],
  searchOptions: {
    // Boost books by a factor of 1.5
    boostDocument: (docId, _term) => {
      if (docById[docId].type === ContentType.BOOK) {
        return 1.5
      } else {
        return 1
      }
    }
  }
})
```

I hope this helps.

**Comment by rickdio** [comment]
Hi @lucaong 

Thanks for your help. This indeed works perfectly!

Do you have any recommendation or tips on the amount of boost?

**Comment by lucaong** [comment]
Welcome :)

Regarding the amount of boost, consider that it is a multiplication factor: a boost of `2` makes a result twice more relevant than it would normally be. I’d try to be conservative and set it to a value not too much bigger than 1, then increase it if necessary.

Unless you really want to have only one type of result first, then all the other types. In that case I would probably partition the result set into two lists, something like:

```javascript
let results = miniSearch.search(…)
let bookResults = []
let otherResults = []

// Assuming that 'type' is in storeFields
results.forEach((result) => {
  if (result.type === ContentType.BOOK) {
    bookResults.push(result)
  } else {
    otherResults.push(result)
  }
})
```

**Comment by lucaong** [comment]
Hi @rickdio ,
I will go on and close the issue for now, as it should be solved, but feel free to comment further if you need more information.
