### ISSUE TITLE
Match diacritics option

### ISSUE THREAD

**Issue by onodera-punpun** [lucaong/minisearch#153]
I don't know if this this already possible, but I would really like the query "guenon" to match both "Guénon" and "Guenon".

**Comment by lucaong** [comment]
Hi @onodera-punpun ,
there is no out-of-the-box treatment of diacritics (because the appropriate way to do that depends on the specific use-case), but it is possible to achieve what you want by normalizing terms using the `processTerm` option. Here is an example:

```javascript
const normalizeDiacritics = (str) => {
  // This solution work with many diacritics on most browsers, but not all
  // (e.g. the Polish `ł` is not handled correctly).
  // Alternatively, one could use a package like:
  // https://www.npmjs.com/package/normalize-diacritics
  return str.normalize('NFKD').replace(/[^\w]/g, '')
}

const miniSearch = new MiniSearch({
  fields: [/* ... */],
  processTerm: (term) => {
    return normalizeDiacritics(term).toLowerCase()
  }
})
```

I hope this helps!

**Comment by onodera-punpun** [comment]
Exactly what I want, thanks!

**Comment by odinho** [comment]
Almost what I'd want. But I would actually want a search for "guénon" to *only* match the one with the diacritics. I've stuffed the index with both terms in the tokenizer, but then you get the problem that searchingn for "gu" it'll match both "guénon" and my stuffed "guenon" term and so its score is artificially high.

Is there a good way to do something like this without too big side effects?

**Comment by sandstrom** [comment]
The search library Sifter (https://github.com/brianreavis/sifter.js/) has support for diacritics. Maybe some inspiration could be taken from that library?

Their implementation is here: https://github.com/brianreavis/sifter.js/blob/master/lib/sifter.js#L444

**Comment by lucaong** [comment]
The implementation in sifter.js is a good reference. Some diacritics though are better normalized to more than one character, for example the German “ü” is usually considered equivalent to “ue”, not to “u”. Ultimately it’s a use-case specific choice, but sifter’s approach is a reasonable one.

**Comment by sandstrom** [comment]
@lucaong 👍🏻
