### ISSUE TITLE
Limiting results

### ISSUE THREAD

**Issue by eloydegen** [lucaong/minisearch#160]
Hi,

Is there a possibility for limiting the results to say, 1000 entries? I have a dataset of around 40k entries and my browser freezes when trying to use this. Or would you say that this project is not suitable for datasets of that size? Thanks.

**Comment by eloydegen** [comment]
I just read #148, which answers my question. I will close this thread.

**Comment by lucaong** [comment]
Hi @eloydegen ,
Thanks for referring to the other existing issue. The only thing I want to say is that 40k documents should not by themselves cause the browser to freeze at search time. If the app does freeze, there might be some problem. A few options:

  - Make sure that the documents are indexed only once. This sounds obvious, but I have seen several projects mistakenly reindexing upon each search
  - Sometimes, what is slow is not retrieving the search results, but rather rendering a lot of them. In these cases, truncating the results to the top N, or using some lazy rendering technique, would solve the problem.
