### ISSUE TITLE
Typescript - minisearch_1.default is not a constructor

### ISSUE THREAD

**Issue by Thomas-1985** [lucaong/minisearch#164]
Hi

package version: 5.0.0
Typesscript: 4.5.5

I want to use minisearch in my project as below

```
import MiniSearch from 'minisearch';
...

    const searchOptions = {
      combineWith: "AND",
      searchOptions: {
        prefix: false,
        fuzzy: false
      }
    }

    const engine = new MiniSearch({
      fields: ['name'],
      searchOptions: searchOptions
      })

    engine.addAll(data);
    const searchResult = engine.search(query);
```

However, i always get an error `TypeError: minisearch_1.default is not a constructor`

It works when using `const MiniSearch = require('minisearch');`

What am i doing wrong here?

**Comment by lucaong** [comment]
Hi @Thomas-1985 ,
that is strange, from the code snippet you posted, there seems to be nothing wrong with your `import`. Since the `require` works, could there be something wrong in your build setup? What's in your `tsconfig.json`?

**Comment by Thomas-1985** [comment]
```
{
   "compilerOptions": {
      "target": "es2020",
      "module": "commonjs",
      "strict": true,
      "strictNullChecks": false,
      "useUnknownInCatchVariables": false,
      "noImplicitAny": false,
      "moduleResolution": "node",
      "outDir": "./build",
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "baseUrl": "src",
      "rootDir": "src",
      "paths": {
         "*": [
            "*"
         ]
      }
   },
   "include": [
      "src/**/*",
      "src/locales/*.json"
   ]
}
```

**Comment by lucaong** [comment]
You probably need to set the [`esModuleInterop` option](https://www.typescriptlang.org/tsconfig#esModuleInterop) to `true` in the `compilerOptions` section of `tsconfig.json`.

**Comment by lucaong** [comment]
I think this fixes your issue, so I’ll close the issue for now, but feel free to reply if it doesn’t.
