### ISSUE TITLE
Question: Best practice for searching multiple types of data?

### ISSUE THREAD

**Issue by kculmback-eig** [lucaong/minisearch#167]
In our application we are planning on having an 'omni' search in the UI where the user can search across multiple data types (e.g. contacts, templates, tags) that don't have many overlapping fields.

What's the best way to handle this with loading the data into minisearch? I've thought of a few options:

1) Load all the data into a single minisearch instance. This would provide the best way to get proper ranking results but would be a lot of fields for minisearch to index.

2) Load all the data but normalize the fields as much as possible. This would be less fields for minisearch to index but would be less flexible in what we can search for a given data type.

3) Create a minisearch instance for each data type. This is the most flexible solution in regards to building indexes but it would be harder for us to build a properly ranked list of results.

4) Something I haven't though of?

Any help/suggestions would be greatly appreciated?

**Comment by lucaong** [comment]
Hi @kculmback-eig ,
it depends a bit on your specific case, but by experience:

  - Option 1 (single MiniSearch instance) is usually the most appropriate if you want to mix different types in the results, sorted by relevance. Having many "sparse" fields, often empty, is usually not a problem for MiniSearch. The way the index is structured does not occupy space or consume index-time or search-time resources for blank fields. If your UI allows for optionally specifying the types to search, that can still be implemented with the `filter` option.
  - Option 3 (separate instance per type) can sometimes be the right way if you prefer to keep different type of results separate, like first contacts, then templates, etc. This does not seem to be your case though.

Normalizing the fields might help where it makes sense, but I would not go overboard with it. I remember one application indexing different types, but all of them having a single `searchableText` field, but it's usually not necessary.
