### ISSUE TITLE
Is it possible to use minisearch in docsify?

### ISSUE THREAD

**Issue by ghost** [lucaong/minisearch#191]
Hi all.

I would like to know is it possible to use minisearch in docsify. *Is it possible to use minisearch in [docsify](https://github.com/docsifyjs/docsify)?*

**Comment by lucaong** [comment]
Hi @codehangen ,
I don't know much about Docsify, but MiniSearch can in principle be used on any JavaScript application, so I'd say yes.

**Comment by lucaong** [comment]
Sure :) have a great day too!
