### ISSUE TITLE
Question: How to set searchOptions to search keywords?

### ISSUE THREAD

**Issue by Daotin** [lucaong/minisearch#194]
Hi, I have a problem, can you help me. Thanks.

my doc is:

```json
[
 {
    "name": "一路向北",
    "album": "十一月的萧邦",
    "lrc": [
      "倒视镜里的世界",
      "越来越远的道别",
      "你转身向背"
    ]
  }
]
```

when I search `倒视镜里的世界` , it can be matched. But when I search `倒视镜`, It will not be match.

So, How can it be matched when searching for `倒视镜`?   Finally, I want to achieve the effect of full-text search.

> I want use `fuzzy` to solve it, but I dont know how to set.

---

Part of the code is as follows (using Vue3):

```js
const doc = [
 {
    "name": "一路向北",
    "album": "十一月的萧邦",
    "lrc": [
      "倒视镜里的世界",
      "越来越远的道别",
      "你转身向背"
    ]
  }
];

const miniSearch = shallowRef(
  new MiniSearch({
    idField: "name",
    fields: ["album", "lrc"],
    storeFields: ["name", "lrc"],
    searchOptions: {},
    extractField: (document, fieldName) => {
      if (Array.isArray(document[fieldName])) {
        return document[fieldName].join(" ");
      } else {
        return document[fieldName];
      }
    },
  })
)

miniSearch.value.addAll(doc);

// when click search
function handleSearch() {
  results.value = miniSearch.value.search('倒视镜')
}
```

Appreciate your help, Thanks :-)

**Comment by lucaong** [comment]
Hi @Daotin ,
If I understand correctly, what you want is prefix search:

```javascript
const miniSearch = shallowRef(
  new MiniSearch({
    idField: "name",
    fields: ["album", "lrc"],
    storeFields: ["name", "lrc"],
    searchOptions: {
      prefix: true, // prefix search, “foo” matches “foobar”
      fuzzy: true // fuzzy search, “foo” matches “fox”
    },
    extractField: (document, fieldName) => {
      if (Array.isArray(document[fieldName])) {
        return document[fieldName].join(" ");
      } else {
        return document[fieldName];
      }
    },
  })
)
```

**Comment by Daotin** [comment]
Hi @lucaong, Maybe I didn't express clearly.  for example, a string like `你转身向背`, when I search `转身` ( The Key words in the middle of the whole sentence), I hope to be able to match. So, probably not the `prefix search`.

**Comment by lucaong** [comment]
Ah, I see. Then unfortunately MiniSearch by default won’t help. The options allow to:

  - Search only for exact match
  - Search for prefix match (`foo` matches `foobar`)
  - Fuzzy search, also called typo-tolerance: it matches strings within a given Levenshtein distance from the query.
 
 Searching in the middle of a word is generally not possible, but there are some strategies that could work. One possibility could be to split a word in all its suffixes, and use prefix search, like explained [here](https://github.com/lucaong/minisearch/issues/130#issuecomment-1044773525). The index would get bigger, but search would match also in the middle of words.

I hope this helps :)

**Comment by lucaong** [comment]
Here is a quick example of what I mean: https://jsbin.com/poloselexa/edit?js,console

**Comment by Daotin** [comment]
OK. It works! Thank you and Have a great day. 😀

**Comment by lucaong** [comment]
Great to hear it helped :)
