### ISSUE TITLE
add storeFields to types definition

### ISSUE THREAD

**Issue by emilianox** [lucaong/minisearch#20]
Hi!
I think that you missed the property **storeFields** in the types declaration:
can you add that?
is in https://github.com/lucaong/minisearch/blob/02553c76068b3bdff4b5c8dcc81d20e12d3944f0/src/index.d.ts#L48

`storeFields: string[],`

thanks!
BTW: love your work! amazing library!

**Comment by lucaong** [comment]
Ooops! Yes, absolutely, thanks for catching that. I miss `storeFields` and `filter`.
I could add them myself at the beginning of next week (I am on vacation now), but I am happy to take pull-requests too.

**Comment by emilianox** [comment]
Great, im going to send a PR today or tomorrow

**Comment by emilianox** [comment]
https://github.com/lucaong/minisearch/pull/21

**Comment by lucaong** [comment]
I merged #21 and released version `v2.1.1`. Thanks @emilianox for your contribution!
