### ISSUE TITLE
Can I multiply the boost by a score in a field?

### ISSUE THREAD

**Issue by reubenfirmin** [lucaong/minisearch#212]
Let's say I have document:

```
doc {
   content: string;
   baseScore: int;
}
```

I could post-process the results and reorder by multiplying in baseScore, but is there a way to do that as part of the query?

Or, alternately, could I do something like:

```
doc {
   content: string;
   primary: boolean;
}
```
...and tell minisearch to boost by X where primary==true?

The one way I can think of to do this is to:

```
doc {
   content: string;
   forfiltering: string;
}
```

Then when I index, I set forfiltering to some unique string, e.g. "thzzz", include that term in all of my queries, and boost forfiltering. But that's hacky, so I'm looking for something more elegant.

**Comment by lucaong** [comment]
Hi @reubenfirmin ,
yes, there is a clean way to boost specific documents based on the value of a field, by using the `boostDocument` search option:

```javascript
// Say that your documents look like this:
const documents = [
  {
    id: 1,
    text: 'Some example text',
    boostFactor: 1.5
  },
  {
    id: 2,
    text: 'Some other example text',
    boostFactor: 0.9
  },
  {
    id: 3,
    text: 'Some more example text',
    boostFactor: null
  }
]

// Keep a map of documents by their ID:
const docById = documents.reduce((byId, doc) => {
  byId[doc.id] = doc
  return doc
}, {})

// Initialize MiniSearch as usual
const miniSearch = new MiniSearch({ fields: ['text'] })

// Upon search, use the `boostDocument` search option to specify a dynamic boosting factor:
miniSearch.search('example', {
  boostDocument: (docId) => docById[docId].boostFactor || 1
})
```

A boost of `1` is neutral, a boost `> 1` increases the score of a result, and `< 1` decreases it.

**Comment by reubenfirmin** [comment]
Awesome! Thanks

**Comment by lucaong** [comment]
At the moment, only the document ID is passed, but I will soon make a new release that will make the `storeFields` fields available. You will soon be able to do something like this:

```javascript
// Initialize MiniSearch as usual
const miniSearch = new MiniSearch({
  fields: ['text'],
  storeFields: ['text', 'boostFactor']
})

// Upon search, use the `boostDocument` search option to specify a dynamic boosting factor:
miniSearch.search('example', {
  boostDocument: (docId, storedFields) => storedFields.boostFactor || 1
})
```

**Comment by lucaong** [comment]
Version `v6.1.0` is published on NPM, including this feature.

**Comment by reubenfirmin** [comment]
Thanks! This is great.
