### ISSUE TITLE
Prefix search enabled/disabled per search field

### ISSUE THREAD

**Issue by Thomas-1985** [lucaong/minisearch#227]
Hi

Is ist possible to enable the prefix search per search field?
I am working on a project where text as well as numbers (prices) ist searchable. Prefix search for the text makes sense and is needed, however when it comes to searching prices and i search for i.e. 50 i also get 500 which is not desired.

Is there a way to fix this and if so, how?

**Comment by lucaong** [comment]
Hi @Thomas-1985 ,
Yes, that is possible: the [`prefix` search option](https://lucaong.github.io/minisearch/modules/_minisearch_.html#searchoptions-1) can accept a function that takes the field name and term, and can return a boolean. You can therefore return `true` for the text fields, and `false` for the phone numbers (the `fuzzy` option also can accept a similar function).

## Example:

```js
const documents = [
  {
    id: 1,
    text: "Some example text",
    phoneNumber: "+49123456789"
  },
  // more documents…
]

const miniSearch = new MiniSearch({
  fields: ['text', 'phoneNumber'],
  searchOptions: {
    prefix: (fieldName) => fieldName !== 'phoneNumber'
  }
})

// These will yield results
miniSearch.search('examp')
miniSearch.search('+49123456789')

// This will NOT yield results, because prefix search is disabled for phoneNumber
miniSearch.search('+49')
```

**Comment by lucaong** [comment]
Sorry! Discard what I said, the function form of the `prefix` option does _not_ take the field name as argument, my bad.

This is a missing feature that I could add. For the moment, one option is to perform two separate searches, one considering the text fields and using prefix match, one considering only the prices, without prefix search, then merge the results.

**Comment by Thomas-1985** [comment]
Thanks a lot, this worked! :)
