### ISSUE TITLE
Switch to stronger typings

### ISSUE THREAD

**Issue by D34THWINGS** [lucaong/minisearch#229]
I've been using `minisearch` for a few weeks now and I think the TypeScript typing is not really there. It's way too loosely typed with too many `any` being returned, this is quite dangerous and should not be done in a modern library.

The configuration options of the MiniSearch class should take into account the keys available given in the dynamic typing:
```ts
type Options<T = any> = {
    /**
     * Names of the document fields to be indexed.
     */
    fields: keyof T[];
}
```

Then the search result should also return only the `storeFields` if present or the entire record otherwise instead of `Record<string, any>` which is quite unsafe to use as you no longer have field validation on it.

If you agree with this I could open a pull request, but it would probably mean going for v7 of the package as this would be a breaking change for TS users.

**Comment by lucaong** [comment]
Hi @D34THWINGS ,
a similar issue was discussed in https://github.com/lucaong/minisearch/issues/208 . In short, the primary goal of MiniSearch is to support both JavaScript and TypeScript users with a simple and flexible API, that scales with user needs. Strict type safety in TS is a desirable feature, but subordinate to the goal above. Ultimately, I think the benefits of introducing such a breaking change do not outweigh the cost of.

The large majority of MiniSearch users come from plain JS, and only need the basic fields option: for those, the path of least friction is to simply require an array of strings. The current API is “additive” for more complex needs: more advanced options are layered on top, without making the basic API more complex.

I understand the appeal of a strict type design, but that tends to impose a level of complexity (even in the type definitions) that most users are not comfortable with. It's ultimately a matter of project direction, but ergonomics matter more than strict type safety for me in this case.

One viable option that does not involve breaking changes is to implement a strictly typed thin wrapper around MiniSearch.

**Comment by lucaong** [comment]
I think that the suggestion made by @juiceo [here](https://github.com/lucaong/minisearch/issues/208#issuecomment-1545352535) is quite interesting, and a pretty good one for an API targeted at TypeScript only. I still believe that imposing such breaking change to everyone would be a bad trade off, but that's the direction I would investigate for a thin wrapper improving type safety for TypeScript users.
