### ISSUE TITLE
case-sensitive dynamic selection during search

### ISSUE THREAD

**Issue by nanliangwu** [lucaong/minisearch#233]
Thank you for providing this awesome Javascript library. I wanna know if it supports case-sensitive dynamic selection during search?

**Comment by lucaong** [comment]
Hi @nanliangwu , thanks for your kind words :)

MiniSearch is fully capable of case sensitive search. The default is to normalize case, but if you want search to be case sensitive, the easiest option is to specify your own normalization:

```js
const miniSearch = new MiniSearch({
  fields: [/* your fields here */],
  processTerm: (term) => term // do not normalize terms
})
```

I hope this helps!

**Comment by lucaong** [comment]
hi @nanliangwu , since I think that the question was answered, and there is no more activity on the issue, I will go on and close it. If your problem is not solved, feel free to comment here, and I will reopen the issue if necessary.
