### ISSUE TITLE
how to index nested field with its value is an array

### ISSUE THREAD

**Issue by jimbung** [lucaong/minisearch#238]
my data is like this:

```json
[{ 
    "id": 1,
    "access": "acc23 15698",
    "category": "Lab",
    "actions": [
        {
            "comment": "9/12/23 BY GSM.~ONE DAY~ACTION WILL BE REPORTED",
            "resultTime": 1694502000,
            "status": "F"
        },
        {
            "comment": "10/12/23 BY GSM.~TWO DAY~ACTION WILL BE REPORTED",
            "resultTime": 1697532400,
            "status": "P"
        }
    ],
    "subcat": "client"
}]
```

how to index "comment" in the array structure "actions"?  and how if there is deeper structure like this (the "game" field in array "suscp"):

```json
[{ 
    "id": 1,
    "access": "acc23 15698",
    "category": "Lab",
    "actions": [
        {
            "comment": "9/12/23 BY GSM.~ONE DAY~ACTION WILL BE REPORTED",
            "resultTime": 1694502000,
            "status": "F",
             "suscp": [{
                  "game":"the game starts on 15:00",
                  "wol": "W"
             }]
        },
        {
            "comment": "10/12/23 BY GSM.~TWO DAY~ACTION WILL BE REPORTED",
            "resultTime": 1697532400,
            "status": "P",
             "suscp": [{
                  "game":"the game starts on 13:20",
                  "wol": "L"
             }]
        }
    ],
    "subcat": "client"
}]
```

Thanks for any comments!

**Comment by lucaong** [comment]
Hi @jimbung ,
you can achieve what you want by specifying a custom `extractField` option. One question is how you want to aggregate the `comment` text from multiple elements of the array. If you simply want to concatenate them, here is how you could do that:

```javascript
const miniSearch = new MiniSearch({
  fields: ['access', 'category', 'comment', 'game', 'subcat'],
  extractField: (doc, fieldName) => {
    if (fieldName === 'comment') {
      return doc.actions && doc.actions.map((action) => action.comment || '').join(' ')
    } else if (fieldName === 'game') {
      const suscp = doc.actions && doc.actions.flatMap((action) => action.suscp || {})
      return suscp.map((s) => s.game || '').join(' ')
    } else {
      return doc[fieldName]
    }
  }
})
```

You can then search as if `comment` and `game` were normal "flat" fields.

I hope this solves your issue!

**Comment by jimbung** [comment]
Hi @lucaong,
Der Code funktioniert wie ein Zauber.
Vielen Dank!

**Comment by jimbung** [comment]
Hi @lucaong,
`const miniSearch = new MiniSearch({
  // Specify the list of fields to index, as if 'comment' and 'game' were not nested
  fields: ['access', 'category', 'comment', 'game', 'subcat'],

  // Specify a custom logic to extract fields from the document
  extractField: (doc, fieldName) => {
    if (fieldName === 'comment') {
      return (doc.actions || []).map((action) => action.comment || '').join(' ')
    } else if (fieldName === 'game') {
      **const suscp = (doc.actions || []).flatMap((action) => action.suscp || {})**
      return suscp.map((s) => s.game || '').join(' ')
    } else {
      return doc[fieldName]
    }
  }
})`
should "action.suscp || {}" in above bold line be "action.suscp || []", since suscp is an array?
I use "action.suscp || {}" and "action.suscp || []", both works.

**Comment by lucaong** [comment]
@jimbung yes, you are absolutely right, it should be `action.suscp || []`. If `suscp` is always present (even as an empty array), it won't matter, but the version with the array is the correct one. I went on and corrected my example above.

**Comment by jimbung** [comment]
Hi @lucaong Thanks a lot for your detailed interpretation! All is clear now.

**Comment by lucaong** [comment]
You are welcome @jimbung ! I will close the issue, but feel free to comment further if more info is needed.
