### ISSUE TITLE
about search result

### ISSUE THREAD

**Issue by jimbung** [lucaong/minisearch#239]
Hi,
When i search sth with the middle part of one word, is cannot return the items.
for example, after create index for
'''
{
title: "this is a test"
}
'''
and i search "es", it returns null.

am I wrong with using it? thanks！

**Comment by lucaong** [comment]
Hi @jimbung ,
MiniSearch by default does not support searching in the middle of a word. It only supports searching at the beginning of the word, using `prefix` search, and/or for slightly misspelled words using `fuzzy` search.

That said, it is possible to implement search in the middle of the world, at the cost of a larger index, by following the instructions in [this other discussion](https://github.com/lucaong/minisearch/issues/194) (and in particular in [this comment](https://github.com/lucaong/minisearch/issues/194#issuecomment-1369229601)).

**Comment by jimbung** [comment]
Hi @lucaong , thank u very much for quick response on the issue.
i tried as the following as the processTerm you mentioned above, but unfortunately some text cannot be searched out (before using processTerm function, they can be searched out).
below is the code, please have a look if i am wrong with somewhere.

```
const suffixes = (term, minLength) => {
  if (term == null) { return []; }
  const tokens = [];
  for (let i = 0; i <= term.length - minLength; i++) {
    tokens.push(term.slice(i));
  }
  return tokens;
}
const idfield = "order_id";
const miniSearch = new MiniSearch({
      idField: idfield,
      fields: ["suscep", "action.comment", "action.game.comment"],
      extractField: (document, fieldName) => {
          const arrFields = fieldName.split(".");
          if (arrFields.length === 2) {
            return (document[arrFields[0]] || [])
              .map((arrField: any) => arrField[arrFields[1]] || "")
              .join(" ");
          } else if (arrFields.length === 3) {
            const tmparr = (document[arrFields[0]] || []).flatMap(
              (arrField: any) => arrField[arrFields[1]] || []
            );
            return tmparr.map((s: any) => s[arrFields[2]] || "").join(" ");
          }

          // Access fields in simple path (such as a.b.c)
          return fieldName
            .split(".")
            .reduce((doc, key) => doc && doc[key], document);
      },
      processTerm: (term) => suffixes(term, 3),
      searchOptions: {
        processTerm: MiniSearch.getDefault('processTerm'),
        prefix: true,
      },
    });
```

Thanks!

**Comment by lucaong** [comment]
Hi @jimbung ,
I did a quick test, only including the `processTerm` logic and excluding the `extractTerm` part, and it seems to work correctly:

```javascript
const suffixes = (term, minLength) => {
  if (term == null) { return []; }
  const tokens = [];
  for (let i = 0; i <= term.length - minLength; i++) {
    tokens.push(term.slice(i));
  }
  return tokens;
}
const miniSearch = new MiniSearch({
      fields: ["text"],
      processTerm: (term) => suffixes(term, 3),
      searchOptions: {
        processTerm: MiniSearch.getDefault('processTerm'),
        prefix: true,
      },
    });

const docs = [{id: 1, text: "something"}, {id: 2, text: 'something else'}]

miniSearch.addAll(docs)

miniSearch.search('thi')
/* >
[
  {
    id: 1,
    score: 0.10047016592300792,
    terms: [ 'thing' ],
    match: { thing: [Array] }
  },
  {
    id: 2,
    score: 0.084675550210326,
    terms: [ 'thing' ],
    match: { thing: [Array] }
  }
]
*/
```

Later today or tomorrow I will probably be able to test your code more in details. In the meanwhile, a few suggestions:

  - make sure you use the latest `MiniSearch` version if you do not already use it.
  - try to find if the problem is with the `extractField` part or the `processTerm` part
  - if possible, provide an example with data to show the issue (ideally, a complete example where some result that you expect to be found is not found). This will help to spot the issue.
 
Good luck!

**Comment by jimbung** [comment]
Hi @lucaong ,
Thanks for quick reply.
I am using "minisearch": "^6.2.0" currently. is it the latest?
I'll check your suggestions later.
Thank you very much!

**Comment by lucaong** [comment]
Yes, its the latest 👍

**Comment by lucaong** [comment]
@jimbung did you manage to resolve your problem?

**Comment by lucaong** [comment]
Thank you @jimbung , happy to know your issue is solved! I will then mark the issue as closed.
