### ISSUE TITLE
Search terms are broken when immediately following unicode whitespace

### ISSUE THREAD

**Issue by th317erd** [lucaong/minisearch#249]
I have found that any term immediately preceded by Unicode white space (not sure if it is all Unicode white space characters, or just certain ones) will fail to be found... always. I have tried every possible search option, and I can not make it work.

Help!

Example (using zero width space: https://unicode-explorer.com/c/200B):
```javascript
let items = [
  {
    id: 'broken-item',
    title: '\u200BHello world!',
    //          ^ zero width space
  },
];

let searchEngine = new MiniSearch({ fields: [ 'title' ], searchOptions: { prefix: true, fuzzy: 0.2 } );
searchEngine.addAll(items);

// Will never be found! :'(
let found = searchEngine.search('hello');
// result: []

// Works fine when not preceded by Unicode white space
found = searchEngine.search('world');
// result: [ { id: 'broken-item', ... } ]
```

**Comment by lucaong** [comment]
I will soon merge #250 to fix this, and create a new release. In the meanwhile, please use the suggestions above to fix this issue.

Thanks again for reporting this issue!

**Comment by th317erd** [comment]
Thank you for the information and helpful examples @lucaong!

I noticed the `tokenizer` and `processTerm` options, but the documentation on them is very poor, and I couldn't understand how to use them.

Would it be possible for me to submit a PR to update the documentation?

I don't think I understand either even now. The `tokenizer` seems simple enough. It just takes the entire "source" text (from each field I assume) and splits it into tokens, yes?

`processTerm` however still confuses me. Your example just made it more confusing. For example:

```javascript
processTerm: (term) => term.toLowerCase().replace(ZERO_WIDTH_SPACES, '')
```

What is `term` here? If I understand the `tokenizer` correctly, a `term` should be one of the split parts, a "token" if you will, yes? So, what is `term` in the context of `processTerm`, and if it is already a "token", then how would `replace(ZERO_WIDTH_SPACES` work? Are you saying that the default `tokenizer` is splitting things such that the zero-width space is remaining part of the first "Hello" term? As in, `'\u200BHello'` is the first token/term?

As you might be able to see from my confusion, I would like to update the documentation if you could point me at the repo.

FYI: Just a thought, this might all be clearer to other developers if `processTerm(term)` was instead called `processTokenIntoTerm`... or even just changing the argument in the documentation from `term` to `token` might make things easier to understand. In any case, I feel the documentation needs to be more descriptive and clearer regarding these two callbacks. Happy to help! Just point me in a direction!

**Comment by th317erd** [comment]
Thank you much again @lucaong!

Heavens no! I wasn't recommending you modify the API interface! That would indeed be a very large breaking change for very little value.

I was just suggesting some possible "visual cues" that might help people understand the documentation. However, you provided it entirely:

Regarding the process that MiniSearch follows, you can think about it as a pipeline:

1. The extractField function extracts the raw text of the field from the document
2. The tokenize function splits the raw text into terms, which correspond roughly to words, but not exactly. This often involves some decision making that is dependent on the specific application. For example, in the text "Amy drank some Coca-Cola", should "Coca" and "Cola" be two different terms, or a single "Coca-Cola" term? In the first case, searching for "Cola" would find this result, but could also bring results containing "Cola" but not "Coca-Cola".
3. Terms are then processed by the processTerm function, for example to normalize them. Think about normalizing case, stemming, replacing diacritics, removing unwanted characters, etc. The results are the terms that will be indexed.
4. The terms are then added to the inverted index, pointing to the original document

☝🏻 This! This is exactly what the documentation needs! Can we please insert this blurb at the top of the `searchOptions` page?

You said all it takes to modify the documentation is to edit the comments in the source code? Would to approve of me adding this as a blurb to the top of the `searchOptions` documentation?

**Comment by lucaong** [comment]
@th317erd sure, documentation improvements are more than welcome 🙂

**Comment by th317erd** [comment]
As promised: https://github.com/lucaong/minisearch/pull/252

Let me know if you'd like any changes!

Thank you for all the help!

**Comment by lucaong** [comment]
Awesome! PR approved, I will merge it. Thanks a lot!

**Comment by th317erd** [comment]
Thank you for all your help!

I am happy to be able to contribute! 😄
