### ISSUE TITLE
Get Mini Search version?

### ISSUE THREAD

**Issue by oiver555** [lucaong/minisearch#251]
I'm using Minisearch in my app, which was published about a year or two ago. I just made an update of the app a few days ago, updating Minisearch to version 5.0.0, everything works fine however, I notice users get this error...

`Fatal Exception: com.facebook.react.common.JavascriptException: Error: MiniSearch: cannot deserialize an index created with an incompatible version`

...when using the old index from the old version of my app, in the updated version of my app. Is there a way I can obtain the version of Minisearch from it's instance, so that I can make a new index when the conditions require it. Or maybe you have a better solution? Thank you for your time and help!

**Comment by lucaong** [comment]
Hi @oiver555 ,
MiniSearch follows semantic versioning: breaking changes are only introduced with major releases. In other words, as long as the first version number does not change (the `x` in `x.y.z`), you can safely upgrade. A common strategy to avoid bad surprises when updating is to pin the major version of the library in your `package.json`, by specifying your dependency as `"minisearch": "^6.3.0"`. This will update MiniSearch automatically to any new minor or patch version, but not if the major version changes (so you can perform the major updates manually when you are ready, checking the CHANGELOG for breaking changes and how to deal with them).

That said, it might be useful to obtain the current version from the MiniSearch instance. This will require some automation during build, I will look into it for the next update.

**Comment by oiver555** [comment]
Understood, thanks for the response and protocol
