### ISSUE TITLE
loadJSONAsync() Ready or Not?

### ISSUE THREAD

**Issue by oiver555** [lucaong/minisearch#266]
Greetings, I notice you have this function in the documentation website loadJSONAsync() but when I try to call it I don't see any code hints for it's existence. I then noticed in the changelog that this function is listed under the title Upcoming (unreleased). So I guess this means that it is not ready yet? If it is ready is there a way I can use it, I can even be a tester if need be. 

For A while now I notice a little hiccup in the UI of my app whenever I load my index and it's coming from  MiniSearch.loadJS. My index is about 25ish mbs. A async version of loadJSON would be a great addition!

**Comment by scambier** [comment]
Ha! I was just looking right now if it was released on npm, I'm the one who wrote the pull request 😅

I personally consider it to be ready, as I've been using it this method in production for 2 months. You should be able to install it like that in your package.json

```json
{
  "dependencies": {
    "minisearch": "github:lucaong/minisearch#4b231376363918b7fa487cb1735a09efb99fe963",
```

This should install minisearch straight from the repository, and pinned at the last commit.

**Comment by oiver555** [comment]
Great News! Thanks very much 👍

**Comment by oiver555** [comment]
Ok so everything is working in the dev build of my react native app. 
Here is how I am importing it.

import MiniSearch from '../node_modules/minisearch/src/MiniSearch'

However when it comes time for me to do a production build I get this error 

![image](https://github.com/lucaong/minisearch/assets/69017748/edd35877-e9d0-415b-a443-506d536e600d)
I went ahead and tried to do the solution which was to run 
npx  patch-package minisearch

When I do this, here is what happens 
![image](https://github.com/lucaong/minisearch/assets/69017748/0bb93440-5e68-4b95-88d5-96ee3eb1e403)

Do you have any suggestions?

**Comment by scambier** [comment]
I've never used patch-package, but from what I understand reading the error
- You made a patch for minisearch
- You updated minisearch (I guess from 6.3.0 to the latest master commit)
- So, the patch you made for 6.3.0 is now potentially invalid for the currently installed version

Solutions:
- Remove the patch if you don't need it anymore
- See if patch-package works on specific commits (instead of versions)
- Fork minisearch to patch it, and install your fork

**Comment by oiver555** [comment]
Got it okay, will give it a shot

**Comment by lucaong** [comment]
@oiver555 @scambier that's right, the feature is not yet on NPM. I will make a new release, hopefully later today.

**Comment by lucaong** [comment]
@oiver555 @scambier version `v7.0.0` is now released on NPM, and it includes this feature.
