### ISSUE TITLE
TypeScript typings for storeFields

### ISSUE THREAD

**Issue by ryan-codingintrigue** [lucaong/minisearch#27]
I think the TypeScript typing for the `storeFields` property might be in the wrong place:

https://github.com/lucaong/minisearch/blob/25f9e04c7a12968ea4074019d820adbc792a381c/src/index.d.ts#L30

Should probably be in the plain `Options` interface:

https://github.com/lucaong/minisearch/blob/25f9e04c7a12968ea4074019d820adbc792a381c/src/index.d.ts#L51

Can file a PR if needed 😄

**Comment by lucaong** [comment]
Ooops... you're absolutely right!

Yes, a PR would be awesome 🙂

**Comment by lucaong** [comment]
Fixed by https://github.com/lucaong/minisearch/pull/28 (thanks again @ryan-codingintrigue), I just released `v2.1.3` including this fix.
