### ISSUE TITLE
this has nothing to do with PHP and MYSQL, right? 

### ISSUE THREAD

**Issue by halukkaramete** [lucaong/minisearch#283]
Hello, as I understand, your wonderful search utility works with a JSON record, downloaded to the client and the entire operation is done withing the browser, correct? 

That means no live look up mySQL's queries to bring results as the user types ahead... 

is it also possible to get the json formed on the fly, for example, take the 3 letters user has entered and trigger a buildJSON call at the 3rd character, submit to your SQL for a query like bring everything you got that matches those 3 letters in the kind of a JSON your engine wants and then leave the rest of the action be taken care of by your engine. 

This way, even if you were to have a 2, 3 hundred thousand record DB, having those 3 characters would significantly reduce the JSON to be dealt with... 

Am I sensing your tool correctly?

**Comment by lucaong** [comment]
Hi @halukkaramete ,
you are right, MiniSearch by itself has no knowledge of PHP or databases. It normally runs in the browser, although it can run on the server side on NodeJS.

It is possible to submit the query to the server for an initial check on the database of the matching records, but that would mean that the candidate records have to be re-indexed upon each query. If the full collection of documents does not fit in the browser, it might be worth using a search server like ElasticSearch.

I hope this helps :)

**Comment by halukkaramete** [comment]
Thank you for your reply. Could you explain what you meant by " If the full collection of documents does not fit in the browser"? 

As to the my idea of getting the json at the 3rd character, I think this would work as we will be paying for the penalty time for  indexing only once. A query like bring all from field that has %abc% would bring a reasonable set assuming user did not screw up on those 3 letters... the rest would be your algorithm taking it over and allowing user to find what they are looking for among those entries in the json that has those 3 chars. I guess we can also do something like %a%b%c% or just %ab% to play with the performance... 

This little change of feature  can make your tool eligible to use 100K records, vastly increasing its adoptance. 
For example, I have to build that functionality right now myself in order to use it. and I will do this, since I loved your tool very much!
