### ISSUE TITLE
Better support for property mangling

### ISSUE THREAD

**Issue by stalniy** [lucaong/minisearch#38]
The issue is that I cannot mangle properties in my app due to destructuring of private properties in minisearch.

I configure [terser](https://github.com/terser/terser#mangle-properties-options) to mangle all properties that start from `_`  but due to destructuring on [this line](https://github.com/lucaong/minisearch/blob/master/src/MiniSearch.js#L480) search in my app doesn't work.

As a temporary workaround I marked `_tree` and `_prefix` as reserved props.

I'd appriate if you could change this and not use properties that stars with `_` in destructuring assignments

**Comment by FranzSkuffka** [comment]
Maybe using `_` as a rather than prefix would do it?

**Comment by lucaong** [comment]
I will create a release avoiding the destructuring of those two fields. In general, I wouldn't change the library to accommodate build tools, as the build tools themselves can be configured, and there are too many possible setups in the wild to account for all of them. In this case though, it makes sense, as it is quite an established convention that variables starting with `_` are private, or unused variables.

In general, the index serialization code is one feature that I want to change in the near future. The current serialization is too tightly bound to a specific inverted index implementation, and could hinder further improvements of `MiniSearch` that have to modify the data structure.

**Comment by lucaong** [comment]
I will close this issue, as it is fixed by [this commit](https://github.com/lucaong/minisearch/commit/ae67af6ed9e06036c390447c2bc9e35861400836) and will be part of the next release.

**Comment by lucaong** [comment]
Released as part of `v2.2.2`
