### ISSUE TITLE
Don't publish minified sources to npm

### ISSUE THREAD

**Issue by Alxandr** [lucaong/minisearch#4]
Minified sources make it incredibly annoying to debug what happens within minisearch. Libraries, in general, should not be published minified, that's an issue for applications to deal with (if they want to). I recommend simply using rollup to bundle the sources together or running babel on the sources directly. I can help with this setup if wanted.

**Comment by lucaong** [comment]
Correct. The upcoming patch release will include the non-minified source on NPM. There will be a npm script to build the minified version (with source maps) if necessary.

Thanks for reporting!

**Comment by lucaong** [comment]
Fixed in `v1.1.1`

**Comment by stalniy** [comment]
@Alxandr anyway, you need proper sourcemaps even to read code transpiled by babel. Sometimes it's a big mess, especially when babel transforms classes to ES5 not in loose mode :)

So, should library authors live transpilation of their libraries to app's deveopers? I don't think so.
