### ISSUE TITLE
Remove all documents

### ISSUE THREAD

**Issue by clibu** [lucaong/minisearch#43]
Luca, first let me say Minisearch is great. I've been battling with FlexSearch for a while _(which seems to be stagnant)_ and finally gave up and moved to Minisearch for our [Clibu Notes](blog.clibu.com) app. 

I did try Minisearch earlier and had some issues which I couldn't reproduce this time around. 😀

I need to be able to remove all documents from the search index and wonder what the most efficient way to do this is. I don't want to iterate all the docs and call ```remove()```. 

Is it safe just to delete the searchEngine instance's and do ```new MiniSearch()``` to start over or do you have another suggestion?

**Comment by lucaong** [comment]
Hi @clibu ,
thanks for the kind words, I am happy you are finding MiniSearch useful!

If you need to remove all documents, the most performant way is indeed to create a new search engine instance. As long as the old instance is not referenced anymore, it will be garbage-collected.

I will possibly add a `removeAll` function in the next release, but it would be doing internally more or less the same, so it would not make a difference in performance. It will be a bit more convenient, just removing the need to re-instantiate `MiniSearch`.

**Comment by lucaong** [comment]
I actually just implemented this pull request: https://github.com/lucaong/minisearch/pull/44

It adds a `removeAll` method. If called with a list of documents, it iterates through them and removes them, if called without arguments it _efficiently_ removes all documents from the index (without iterating through them).

I will create a new release, it might help you for your use case.

**Comment by lucaong** [comment]
And `v2.3.1` is now on NPM, with the new `removeAll` method. This should provide a solution for your use-case, so I am closing this issue, but feel free to comment on it in case you experience any problem.
