### ISSUE TITLE
Feature request: expose SearchableMap

### ISSUE THREAD

**Issue by rfox12** [lucaong/minisearch#46]
I love MiniSearch, but a small change could make it a lot more usable for my use case.  I pre-index a company's user directory on the server side and then send it to the browser--works great.  What I'd like to do, however, is have a web page which lists all of the users.  Without access to "_index" (the root SearchableMap), I can't really get documents outside of the search functionality.  If you exported SearchableMap, and provided an accessor I think MiniSearch could handle all of my client-side needs... and then when I need detail I can fetch the full record from the server.

**Comment by lucaong** [comment]
Hi @rfox12 , thanks for your kind words!
You can actually access the index with `miniSearch._index`, even though it's a bit of an internal implementation detail at the moment.

I could make it explicitly public, exposing a function like `miniSearch.getIndex()` (or something similar) in a new release, but I am not sure it would help in your case: the `SearchableMap` is the _inverted_ index. You can think about it as a map of terms to the documents/fields that they appear in. If you enumerate it, each entry will be a `[term, postingList]` tuple, not a document (user in your case).

I think the best would be to just send the list of users to the client too. I would even suggest trying to send _only_ the list of users, avoid creating the index server-side, and index them client side on each page reload: unless your user records are huge, it's usually very fast, and you would not have to care about recreating the index server side when a user gets added or modified.

Or am I misunderstanding your case?

**Comment by rfox12** [comment]
Makes sense--thank you for the reply and suggestion.  I noticed the _documentIds field and is there perhaps another way to get their stored fields directly?

Alternatively is there a way to run a search that says "match everything"?

**Comment by rfox12** [comment]
Also a quick note...  the user database is just my first use case--you're right I could just send the raw user collection.  But I have other documents that are very text-heavy--and sending them raw would be MUCH bigger than sending the pre-compiled index.

**Comment by lucaong** [comment]
Technically yes, the `_storedFields` property is a map of `shortId` to the stored fields, so its values are the stored fields of each document.

There are two problems with it though: the first is that this field is an implementation detail (but it's technically accessible). The second problem is that the `shortId` is not the original document `id`, but rather an internally compressed ID (to save memory, especially if the original IDs, that occur many times in the internal data structures, are long). There is another field called `_documentIds` that maps `shortId` to the original ID.

Your issue gives me a cool idea though. I could expose a few methods to retrieve the stored fields given the document ID, and to iterate the stored fields of each document (the order won't be guaranteed). This could serve your use case, and be part of the public API.

**Comment by rfox12** [comment]
Sounds promising!  As long as there is a .get() method by ID, my client-side javascript will take care of the sorting and such.  It would nice to use MiniSearch as my search index and "browse index".  98% of the time I don't need to pull the full document from the server.

**Comment by lucaong** [comment]
Meanwhile, one way to achieve a "get by ID" feature is to index the ID field and perform an exact match on it:

```javascript
const miniSearch = new MiniSearch({
  fields: ['id', /* your other fields... */],
  storeFields: [ /* ... */]
})

// Get by ID is an exact match search on the ID field:
miniSearch.search(someId, { fields: ['id'] })
```

This works if the ID is a string, otherwise you would have to use a custom `extractField` to turn it into a string.

If you also store the ID as a stored field, you could then get all stored fields like this:

```javascript
Object.values(miniSearch._storedFields)
```

Note that this is using an internal API, so it might break in newer versions. I will think about the best way to provide such features as a public API.
