### ISSUE TITLE
Crash when searching "constructor"

### ISSUE THREAD

**Issue by scambier** [lucaong/minisearch#49]
Hello! First, thanks for Minisearch, that's a useful, well-designed lib.

I've found an interesting bug though: I use Minisearch for technical markdown documents, and some of them contain the word "constructor". Minisearch crashes when I'm searching for any term that begins the word "constructor" (like "c", "con", "const", "construct"...)

The code I'm using for the search:

```ts
const results = this.miniSearch.search(search, { prefix: true, boost: { title: 10 } })
```

Here's the (webpack-mangled) outputted error:

```
TypeError: results[documentId].match[term].push is not a function
    at eval (index.js?7f7f:1732)
    at Array.forEach (<anonymous>)
    at eval (index.js?7f7f:1714)
    at Array.reduce (<anonymous>)
    at termResults (index.js?7f7f:1703)
    at MiniSearch.executeQuery (index.js?7f7f:1521)
    at eval (index.js?7f7f:1295)
    at Array.map (<anonymous>)
    at MiniSearch.search (index.js?7f7f:1294)
    at FilesNotesRepository._callee6$ (notes-files-repository.ts?700d:132)
```

index.js:1732 refers to `results[documentId].match[term].push(field);` in this code:

```js
    Object.entries(ds).forEach(function (_ref15) {
      var documentId = _ref15[0],
          tf = _ref15[1];
      var docBoost = boostDocument ? boostDocument(self._documentIds[documentId], term) : 1;

      if (!docBoost) {
        return;
      }

      var normalizedLength = self._fieldLength[documentId][fieldId] / self._averageFieldLength[fieldId];
      results[documentId] = results[documentId] || {
        score: 0,
        match: {},
        terms: []
      };
      results[documentId].terms.push(term);
      results[documentId].match[term] = results[documentId].match[term] || [];
      results[documentId].score += docBoost * score(tf, df, self._documentCount, normalizedLength, boost, editDistance);
      results[documentId].match[term].push(field);
    });
```

Thank you

**Comment by lucaong** [comment]
Hi @scambier , thanks a lot for reporting this!

A solution for this issue is upcoming.

**Comment by lucaong** [comment]
This issue (and other related ones that I discovered thanks to your report) is fixed by #50 

I will now merge it and create a new release.

Thanks again!

**Comment by lucaong** [comment]
Version `v2.4.1` including the fix for this issue is now published on npm.

**Comment by scambier** [comment]
You fixed it in less time than it took me to iteratively discover what was crashing :D

**Comment by lucaong** [comment]
The bug was subtle and not easy to isolate, but after your report it was rather easy to fix (and uncovering other similar ones) :)
