### ISSUE TITLE
Is minisearch able to work with nested object fields?

### ISSUE THREAD

**Issue by zachsa** [lucaong/minisearch#54]
Hi, I came across this library via googling for browser-compatible Elasticsearch alternatives. It looks great and I'm excited to try it out!

My use case is that I am retrieving a subset of results from an Elasticserch endpoint, that I would like to be searchable in an offline environment. These documents have a nested structure:

```js
const docs = [
  {
    field: [
      { subfield: 'some value }
    ] 
  },
  {
    field: [
      { subfield: 'some other value }
    ] 
  },
  etc.
]
```

Elasticsearch allows for specifying searching subfields, like so:

```json
"query": {
  "bool": {
    "must": [
      {
        "multi_match": {
          "query": "other",
          "fields": [
            "field.subfield"
          ],
          "fuzziness": "AUTO"
        }
      }
    ]
  }
},
```

Is it possible to achieve a similar search with this library?

**Comment by lucaong** [comment]
Hi @zachsa ,
yes, this is possible, by specifying a custom `extractField` option, which allows complete customization of how fields are extracted from your documents. You can check out [this example](https://github.com/lucaong/minisearch#field-extraction) in the README, which shows a nested fields case, similar to yours.

**Comment by zachsa** [comment]
Thank you for such a quick reply! That looks great. Thanks very much for such a helpful and open source library

**Comment by lucaong** [comment]
Thanks for the kind words :) I'll close the issue, as I assume that your question was answered, but feel free to comment and I will reopen it if necessary
