### ISSUE TITLE
Serialization?

### ISSUE THREAD

**Issue by chrisspen** [lucaong/minisearch#55]
I can't find any mention of this in the docs, but is there any way to save/export/serialize an index once created? It would be nice to be able to save an index to a file and then load that string via an ajax call instead of having to retrieve and load all the documents for each request.

**Comment by lucaong** [comment]
Hi @chrisspen ,
Yes, as a matter of fact you can use the methods [toJSON](https://lucaong.github.io/minisearch/MiniSearch.html#toJSON) (you would not directly call it, but rather call [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) passing the MiniSearch instance) and [loadJSON](https://lucaong.github.io/minisearch/MiniSearch.html#.loadJSON).

There are a few caveats though. The first is that you have to ensure to pass to `loadJSON` the same options that you used for indexing. The second is that, while deserializing the index is fast, transferring and parsing JSON can be slow, so my recommendation is to check if re-indexing is fast enough.

By all means use serialization if it’s the best option for you, but re-indexing on every load is often fast enough, and lets you avoid the complexities of caching and invalidating the index.

I hope this helps!

**Comment by lucaong** [comment]
I also just expanded and clarified the documentation a bit regarding serialization/deserialization, as you are right that it was a bit lacking. GitHub is currently having some hiccups, so the documentation website might not be immediately updated, but will hopefully soon be.

**Comment by lucaong** [comment]
@chrisspen this should answer your question, so I will close the issue for now, but feel free to comment on it if more information is needed.
