### ISSUE TITLE
Use extractField to extract document id field

### ISSUE THREAD

**Issue by mquinn-leverege** [lucaong/minisearch#59]
I've found that using a document structure with an id that is nested, like this for example where `tracker.id` is the document id:
```
{
  tracker : {
    id : 'documentId',
    ...
  },
  asset : { ... }
}
```
is not possible. I'm not sure if there are other considerations preventing this, but it seems as if using extractField to extract the idField in addition to regular fields might solve the issue. I would like to avoid changing the document structure if possible.

**Comment by lucaong** [comment]
@mquinn-leverege thanks for reporting this. Yes, I agree that it would be nice to be able to tread the `id` field like the other fields via `extractField`. I'll look into this, it might impact a few places.

**Comment by lucaong** [comment]
Hi @mquinn-leverege , this issue is resolved by [this commit](https://github.com/lucaong/minisearch/commit/2e70b76dfcace55f53675bb29d6e18b7e0e83217), now the ID field is consistent with the other fields, and its extraction can be customized with `extractField`.

This change is already released as part of version `v2.5.0`. This should solve your case, so I will close this issue, but feel free to comment if not.

**Comment by noraj** [comment]
@lucaong I have a project where I have no uniq field but I could have a uniq string by combining three fields.

Could I do something like

```js
idField: ['field1', 'field2', 'field3']
```

or

```js
function join(...strings) {
  return strings.join('')
}
...
idField: join('field1', 'field2', 'field3')
```

**Comment by lucaong** [comment]
Hi @noraj ,
Yes, you can use `extractField` to implement a “virtual field”:

```javascript
const miniSearch = new MiniSearch({
  fields: […],
  extractField: (document, fieldName) => {
    if (fieldName === 'id') {
      return `#{document['field1']}-#{document[field2]}`
    } else {
      return document[fieldName]
    }
  }
})
```

**Comment by noraj** [comment]
Thanks it works well

```js
const miniSearch = new MiniSearch({
  fields: […],
  extractField: (document, fieldName) => {
    if (fieldName === 'id') {
      return `${document.field1}-${document.field2}`
    } else {
      return document[fieldName]
    }
  }
})
```

**Comment by noraj** [comment]
PS: It could be nice to create a expo gallery in the documentation or github wiki to link projects using minisearch so people could look at real-life/production examples.
