### ISSUE TITLE
Bug when removing documents whose fields are indexed via extractField

### ISSUE THREAD

**Issue by ahri** [lucaong/minisearch#60]
I reproduced this on 2.5.0 today:

```js
const MiniSearch = require('minisearch');

const miniSearch = new MiniSearch({
  fields: ['data.title'],
  storeFields: ['id'],
  extractField: (document, fieldName) => fieldName.split('.').reduce((doc, key) => doc && doc[key], document)
})

const
  item1 = {id: 1, data: { title: "foo"} },
  item2 = {id: 2, data: { title: "bar"} };

miniSearch.addAll([item1, item2]);

console.log(miniSearch.search("foo"));

miniSearch.remove(item1);

console.log(miniSearch.search("foo")); // should be an empty list, but contains:

/*
[
  {
    id: undefined,
    terms: [ 'foo' ],
    score: 0,
    match: { foo: [Array] }
  }
]
*/
```

I couldn't repro without `extractField` config.

It's not critical since I can either normalize items into flatter structures, or filter the result for `undefined` in my `id`s, but I thought you'd like to know.

[Repro'd interactively for your convenience](https://repl.it/@methiant/minisearch-extractfield-bug).

**Comment by lucaong** [comment]
Thanks for reporting @ahri !
I might have introduced this bug in the latest release, I will have a look

**Comment by ahri** [comment]
I think I was on 2.4.4 earlier today before I saw the release, it was also broken in there, hopefully that helps point you in the right direction!

I've only just started using your library, it seems really nice :)

**Comment by lucaong** [comment]
Hi @ahri, as you already found, it was an older bug. It was a bit more subtle than I expected, but [it is now fixed](https://github.com/lucaong/minisearch/commit/7b2a80c33b91f2c5231d955521bd362807729d20).

I just released version `v2.5.1`, including this fix, on npm.

Thanks again!

**Comment by ahri** [comment]
It works! Super fast bug fix, and the shortest-lived workaround I've ever written! 🥇

**Comment by lucaong** [comment]
😄 glad to help, and happy that we caught this sneaky bug. The snippet to reproduce it was super helpful.
