### ISSUE TITLE
is it possible to make the records clickable?

### ISSUE THREAD

**Issue by creativemacmac** [lucaong/minisearch#61]
hey there :) minisearch is really cool :) but is it possible to make the links clickable?

**Comment by lucaong** [comment]
Hi @creativemacmac , thanks for the kind words :)

Yes, it's definitely possible to make the search results clickable, but it's not something that the `MiniSearch` library directly takes care of: `MiniSearch` only implements the search engine logic, taking a query and returning an array of matching results. It does not provide any UI, which is up to the developer to implement.

The [demo application](https://lucaong.github.io/minisearch/examples/) in the `examples` folder of this repository, for example, uses React JS to implement the UI of a song search application. If you wanted to make the results clickable in the demo app, you would change the [`Song` component](https://github.com/lucaong/minisearch/blob/master/examples/src/app.js#L191) and wrap it in a `<a href="...">...</a>`.

Note that `MiniSearch` does not depend in any way on React, so you can use your framework of choice (or no framework at all) for the UI. That's also why `MiniSearch` does not come with a UI, and leaves the task to you. That said, it would be nice to have search UI libraries for popular frameworks like React, Vue, etc. based on `MiniSearch` :)

Or did I misunderstand your question completely?

**Comment by creativemacmac** [comment]
Hi again

No you got me completely right and thanks a gazilion for your thorough reply :) Minisearch is phenomenal and love that it's platform agnostic (react, vue, angular) so will go rave about minisearch right now!! :) Please keep up the good work and remember to do a bit of marketing because I found minisearch a bit by chance :)

**Comment by lucaong** [comment]
Really glad you like it :) thanks for the support!
