### ISSUE TITLE
Array fields like tags or list

### ISSUE THREAD

**Issue by camillo777** [lucaong/minisearch#63]
Does minisearch support also searching on array fields like a list of tags or a list of authors?

For example find where tags contains both "a and "b" values.

**Comment by lucaong** [comment]
Hi @camillo777 ,
while MiniSearch expects strings, you can easily make this work with a custom field extractor, by concatenating the array elements (for example with a space):

```javascript
const documents = [
  { id: 1, title: 'The Chemical Basis of Morphogenesis', authors: ['Turing'] },
  { id: 2, title: 'Synthesis of the Elements in Stars', authors: ['Burbidge', 'Burbidge', 'Fowler', 'Hoyle'] }
]

const miniSearch = new MiniSearch({
  fields: ['title', 'authors'],

  // Custom extractField function that can deal with arrays
  extractField: (document, fieldName) => {
   if (Array.isArray(document[fieldName])) {
    return document[fieldName].join(' ')
   } else {
    return document[fieldName]
  }
})

miniSearch.addAll(documents)

miniSearch.search('Hoyle')
//=> [{ id: 2, ... }]
```

I hope this solves your case.

**Comment by lucaong** [comment]
I will close this issue, as I think my comment solves your case, but feel free to comment if it does not.

**Comment by lucaong** [comment]
To more precisely answer your question, I edited my answer adding an example of matching documents where the array field contains "both A and B".
