### ISSUE TITLE
Partial Searches

### ISSUE THREAD

**Issue by electic** [lucaong/minisearch#66]
Great library. I wanted to ask about partial searches. What if you index the following titles:

`fox trot bax`

And you search for 'fo' however the term 'fox' is not returned. How can I accomplish something like this?

**Comment by lucaong** [comment]
Hi @electic 
if I understand your question correctly, what you are looking for is prefix search. Luckily, it's just an option away:

```javascript
miniSeach.search('fo', { prefix: true })
```

**Comment by electic** [comment]
Nice! I appreciate the help!
