### ISSUE TITLE
Typescript - MiniSearch.default is not a constructor

### ISSUE THREAD

**Issue by dizhang168** [lucaong/minisearch#68]
Hi there! I am using minisearch with my Typescript project and I am really liking `minisearch`. However, I am having some difficulties with instantiating a MiniSearch using the build-in types.

I have the latest version: `3.0.0`.
The code looks something like this:
```TS
import * as MiniSearch from 'minisearch';

const miniSearch = new MiniSearch({
    fields: fieldsWithLabel,
    idField: 'id',
  });
```

I get the error:
```
This expression is not constructable.
  Type 'typeof import("/PROJECTPATH/node_modules/minisearch/dist/types/index")' has no construct signatures.ts(2351)
```

If I try to do:
```TS
import * as MiniSearch from 'minisearch';

const miniSearch = new MiniSearch.default({
    fields: fieldsWithLabel,
    idField: 'id',
  });
```
I get this error:
```
TypeError: MiniSearch.default is not a constructor
```

For now, my workaround is that I added my own types at `types/miniSearch/index.d.ts` with:
``` TS
declare module 'minisearch';
```

But I would much rather use the extensive typing build within the module. Do you know how to fix this?

**Comment by lucaong** [comment]
Hi @dizhang168 ,
The `MiniSearch` is the default export, therefore you need to import it as such:

```javascript
// Wrong
import * as MiniSearch from 'minisearch'

// Correct
import MiniSearch from 'minisearch'
```

I hope this helps.
