### ISSUE TITLE
Feature request: prioritization of prefix search

### ISSUE THREAD

**Issue by sorawee** [lucaong/minisearch#78]
Hi! Thanks for this wonderful tool.

In a project that uses minisearch, there are terms that are very short. E.g., there are terms like `try`, `try_all`, `r`, etc. This creates a dilemma: by setting `prefix: term => term.length > 3`, when searching for `try`, `try_all` would not be included in the search result. However, by setting `prefix: true`, it is also unsatisfactory, because when searching for `r`, other results that start with `r` appear before `r`.

Is it possible to give weight so that exact match results come first, followed by prefix match results, followed by fuzzy match results?

Thanks!

**Comment by lucaong** [comment]
Hi @sorawee , thanks for your kind words!

If I understand correctly, the feature you are requesting is already implemented: by default, exact match is scored the highest, and prefix and fuzzy match are scored lower, depending on the distance to the actual term. Therefore, if you set `prefix: true` and search for `hi`, a result containing the term `hi` will have a higher score than one containing the word `high`, which in turn will have a higher score than results containing the term `highland`.

As an example, in the [demo application](https://lucaong.github.io/minisearch/examples/), if you search for `be`, you will see results containing the term `Be` coming before results containing `Ben` or `Belong`.

The relative weight is by default `1` for exact match, `0.9` for fuzzy match, and `0.75` for prefix match. These relative weights can also be customized with the [`weight` search option](https://lucaong.github.io/minisearch/modules/_minisearch_.html#searchoptions-1).

As I now look at the code, I realize that there might be a bug with the weights customization, but the defaults should work for your case.

**Comment by lucaong** [comment]
Hopefully my reply above solves your problem, so I will close this issue. If you still have doubts, feel free to comment more on this issue.
