### ISSUE TITLE
Struggling with tokenization

### ISSUE THREAD

**Issue by pekq** [lucaong/minisearch#82]
It's better to show the problem I'm facing through this example:
https://stackblitz.com/edit/react-yhek3j?file=src%2FApp.js

With query string: `workshop a` the result is expected; the correct item is returned and *nothing more*.
With query string: `track 2` the result is expected; the correct items are returned and *nothing more*.
With query string: `admiral` the result is expected; the correct item is returned and *nothing more*.

Now, where my approach fails is when `admiral shepard` query string is given. There are no results. It should return the first item.

Is there an approach where all four cases would return expected results.

Thanks for this quality project and I appreciate any help. Let me know if you need more details.

**Comment by lucaong** [comment]
Hi @pekq ,
I think the problem is that you are specifying different tokenizers for indexing and search:

```javascript
// From your example in utils.js

new MiniSearch({
    /* ...omitted lines... */
    tokenize: (text, fieldname) => {
      if (fieldname === "tags") {
        return text.split("|");
      }

      return text.split(SPACE_OR_PUNCTUATION);
    },
    searchOptions: {
      /* ...omitted lines... */
      tokenize: (text, fieldname) => {
        // If the query does not contain "|", it will produce a single big token,
        // which is not what you want for searches of multiple words
        return text.split("|");
      }
    }
  })
```

What you probably wanted was to split search queries by space or punctuation, which you can do with:

```javascript
new MiniSearch({
    /* ...omitted lines... */
    tokenize: (text, fieldname) => {
      if (fieldname === "tags") {
        return text.split("|");
      }

      return text.split(SPACE_OR_PUNCTUATION);
    },
    searchOptions: {
      /* ...omitted lines... */
      tokenize: (text, fieldname) => {
        return text.split(SPACE_OR_PUNCTUATION);
      }
    }
  })
```

A final note, instead of copying the SPACE_OR_PUNCTUATION constant, you could use the default tokenizer, which you can obtain as `MiniSearch.getDefault('tokenize')`. Your code would then become:

```javascript
const defaultTokenize = MiniSearch.getDefault('tokenize')

new MiniSearch({
    /* ...omitted lines... */
    tokenize: (text, fieldname) => {
      if (fieldname === "tags") {
        return text.split("|");
      }

      return defaultTokenize(text, fieldname);
    },
    searchOptions: {
      /* ...omitted lines... */
      tokenize: defaultTokenize
    }
  })
```

I hope this solves your problem :)

**Comment by pekq** [comment]
Thanks @lucaong!

I'm afraid this doesn't solve my problem completely.
You approach indeed solves the problem with `admiral shepard` query string as it properly tokenizes the title attribute. However, it fails with the two other requirements I have.

> With query string: `workshop a` the result is expected; the correct item is returned and nothing more.
> With query string: `track 2` the result is expected; the correct items are returned and nothing more.

If `workshop a` is given for example, your approach returns all four items. It should only return the first item as it is the one with this tag. This requirement is fulfilled in my approach.

Maybe there isn't a way to handle all these requirements but only a set of them?

**Comment by lucaong** [comment]
I see now, I had misunderstood your goal.

You have a bit of a trade off between precision (returning only relevant results) and recall (returning all relevant results).

I think you have several options. The first and simplest is prioritizing for recall, and let the relevance sorting help with precision. The idea is that you might get some irrelevant results, but you don't miss any relevant one, and relevant ones generally come first. This solution can be achieved with a much simples setup (default tokenizer, join tags with space, and just use boost to give priority to results matching inside tags). [Here is an example](https://stackblitz.com/edit/react-5cxkbk?file=src%2Futils.js): as you can see, if you search for `workshop a` or `track 1` you get all results, but the ones you want are on top.

The second solution is to perform more than one search, on different fields and with different settings (such at `tokenize` or `combineWith`), and merge the results. This is a bit more complicated, and relies on more assumptions, but could get you exactly the result you want. [Here is an example](https://stackblitz.com/edit/react-1fmsyz?file=src%2FApp.js).

The third approach is to change the UI to allow the user to select if they want to search by tag or by text. Or, if you have a limited set of tags, to treat them as a category and use the `filter` option to allow only results with the tag specified by the user. If tags are to be considered differently than full-text fields, this approach is probably the best.

**Comment by pekq** [comment]
> The second solution is to perform more than one search, on different fields and with different settings, and merge the results.

More than one search - how I didn't think of that. Thank you! I'll close this issue as resolved.
