### ISSUE TITLE
Search in the middle of string ?

### ISSUE THREAD

**Issue by ButuzGOL** [lucaong/minisearch#83]
Is it possible to search in the middle
name: 'AH Medical Supplies'
query: 'edi'
"Medical" found
?

**Comment by lucaong** [comment]
Hi @ButuzGOL ,
no, this feature is not provided by MiniSearch, which focuses on prefix search and fuzzy search. Fuzzy search might find results if the search query is close enough to the actual term, but beyond this it is out of scope for MiniSearch.

If you need this kind of feature, you can try [Lunr](https://lunrjs.com/), which allows for queries like “*edi*” to mean any term that contains “edi”.
