### ISSUE TITLE
Prefix strategy is good for search-as-you-type ONLY for last token

### ISSUE THREAD

**Issue by patarapolw** [lucaong/minisearch#90]
I also wrote the issue here. - https://github.com/nextapps-de/flexsearch/issues/217

Also, wouldn't it be more intuitive for people, esp. non-technical; if `combineWith: 'AND'` by default? (Not like lunr.js, I know.)

**Comment by lucaong** [comment]
Hi @patarapolw ,
I see what you mean. In MiniSearch, it is actually possible, by specifying a function as the `prefix` search option, that returns true if the term is the last one in the query:

```javascript
miniSearch.search('eye ca', {
  prefix: (term, i, terms) => i === terms.length - 1
})
```

Regarding OR vs AND, it’s a matter of recall vs. precision. I think that higher recall is often a better default, but it very much depends on the use case.

In general, I strive to make MiniSearch versatile enough to be a good building block for diverse use cases.

I am closing the issue for now, as I think this solves it, but definitely feel free to comment further if not.
