### ISSUE TITLE
method addFieldLength () should there be removeFieldLength?

### ISSUE THREAD

**Issue by Lee182** [lucaong/minisearch#97]
Hi looking at src/minisearch I realise that when removing an document that `_fieldLength` is left unchanged.
I realised this doesn't lead to any bugs but say garbarge collection is worth deleting this value, or does it mess up the ongoing average collection.

Thanks.
 ```
delete this._fieldLength[shortDocumentId]
````

**Comment by lucaong** [comment]
You are right, I will soon work on a fix

**Comment by lucaong** [comment]
It's fixed in the latest release `v3.0.3`, just published on NPM. Thank you @Lee182 for reporting!

**Comment by Lee182** [comment]
No worries thanks for this small libary.
